# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Github - test' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Github - test
pod 'MJExtension', '~> 3.0.13'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'CYLTableViewPlaceHolder', '~> 1.0.8'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 3.8.2'

  target 'Github - testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
